### ISSUE TITLE
Compiler crash on v2.3.0: cannot resolve reference toRefinedTypeOps.type.Mirror

### ISSUE THREAD

**Issue by jnicoulaud-ledger** [Iltotore/iron#190] opened 2023-11-03 13:28 UTC
**Describe the bug**
Scala environment: JVM
Scala version: 3.3.0
Iron version: 2.3.0

**Reproduction steps**
The steps to reproduce the described issue
- upgraded my multi module project from iron 2.2.1 to 2.3.0
- switched all `RefinedTypeOpsImpl` to `RefinedTypeOps` for opaque types
- example diff:
![image](https://github.com/Iltotore/iron/assets/102984500/70c1cd2a-d676-4ea8-9977-d2a31f288574)

**Expected behavior**
Compilation successful

**Current behavior**
Compilation fails with error:
```
dotty.tools.FatalError: cannot resolve reference to type io.github.iltotore.iron.RefinedTypeOps$package.RefinedTypeOps.type.Mirror
the classfile defining the type might be missing from the classpath while running MegaPhase{elimErasedValueType, pureStats, vcElideAllocations, etaReduce, arrayApply, elimPolyFunction, tailrec, completeJavaEnums, mixin, lazyVals, memoize, nonLocalReturns, capturedVars} on /runner/_work/cloud-sync-backend/cloud-sync-backend/modules/api/src/main/scala/co/ledger/cloud_sync/api/sync/package.scala
[error] cannot resolve reference to type io.github.iltotore.iron.RefinedTypeOps$package.RefinedTypeOps.type.Mirror
[error] the classfile defining the type might be missing from the classpath
```

**Comment by Iltotore** [comment] 2023-11-03 14:20
Sometimes, name changes like this mess up with incremental compilation. Did you try to clean the compiler cache?

**Comment by jnicoulaud-ledger** [comment] 2023-11-03 16:29
Yes, it was a clean build. Also tried removing wartremover, scalafix and upgrading to scala 3.3.1 with same result. I will try to reduce my project to the bare minimum...

**Comment by Iltotore** [comment] 2023-11-04 07:15
It would also be useful to know where the compiler produces this error. Does it occur when compiling the file containing your new types or when compiling a file using them?

**Comment by jnicoulaud-ledger** [comment] 2023-11-04 10:25
I created a minimal reproducing project here: <https://github.com/jnicoulaud-ledger/iron-issue-190-reproducer>
You can see the compiler in the CI: https://github.com/jnicoulaud-ledger/iron-issue-190-reproducer/actions/runs/6754239254/job/18361529999#step:4:32
(gave you push access to this repo if you want to experiment)

**Comment by Iltotore** [comment] 2023-11-04 14:47
This compiles: https://github.com/jnicoulaud-ledger/iron-issue-190-reproducer/tree/fix/issue-190

The Tapir's Iron integration probably just needs to be updated.

**Comment by Iltotore** [comment] 2023-11-04 16:33
This PR should solve this issue once merged: https://github.com/softwaremill/tapir/pull/3298

For the time being, you can use the code I pushed on https://github.com/jnicoulaud-ledger/iron-issue-190-reproducer/tree/fix/issue-190

**Comment by jnicoulaud-ledger** [comment] 2023-11-04 17:06
I could I have thought of that :facepalm: thank you :)

**Comment by Iltotore** [comment] 2023-11-06 08:11
The [PR](https://github.com/softwaremill/tapir/pull/3298) got merged. Feel free to open a new issue if the problem is still present.

Note that you will probably need to wait for Tapir to release a new version.

**Closed by Iltotore** 2023-11-06 08:11 UTC
Labels: bug
